### Add User ###

POST http://localhost:5000/user/add_user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}

### CHECK FOR CORRECT LOGIN ###
POST http://localhost:5000/user/check_login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}

### CHECK FOR INCORRECT LOGIN ###
POST http://localhost:5000/user/check_login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password1234"
}

### CHECK FOR INCORRECT LOGIN ###
POST http://localhost:5000/user/check_login
Content-Type: application/json

{
  "email": "johndoe1@example.com",
  "password": "password123"
}

### GET ALL USERS ###
GET http://localhost:5000/user

### GET ALL PCS ###
GET http://localhost:5000/pc/

### ADD PC ###
POST http://localhost:5000/pc/add_pc
Content-Type: application/json

{
  "user_id": 1,
  "hardware_uuid": "ABC123",
  "client_name": "Test Client"
}
### GET PCs OF USER 1 ###
GET http://localhost:5000/pc/user/1
