### Add User ###
POST http://localhost:8000/user/add_user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}

### CHECK FOR CORRECT LOGIN ###
POST http://localhost:8000/user/check_login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}

### CHECK FOR INCORRECT LOGIN ###
POST http://localhost:8000/user/check_login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password1234"
}

### CHECK FOR INCORRECT LOGIN ###
POST http://localhost:8000/user/check_login
Content-Type: application/json

{
  "email": "johndoe1@example.com",
  "password": "password123"
}

### GET ALL USERS ###
GET http://localhost:8000/user

### GET ALL PCS ###
GET http://localhost:8000/pc/

### ADD PC ###
POST http://localhost:8000/pc/add_pc
Content-Type: application/json

{
  "user_id": "1",
  "hardware_uuid": "4C4C4544-0052-5210-8050-C8C04F385932",
  "client_name": "Test Client"
}

### ADD PC with non excistent user ###
POST http://localhost:8000/pc/add_pc
Content-Type: application/json

{
  "user_id": "1000",
  "hardware_uuid": "4C4C4544-0052-5210-8050-C8C04F3859312",
  "client_name": "Test Client"
}

### GET PCs OF USER 1 ###
GET http://localhost:8000/pc/user/1


### POST Request to Insert Timeseries Data###
POST http://localhost:8000/data/
Content-Type: application/json

{
    "pc_resources": "relevant_list",
    "connection_data": "Ethernet",
    "application_data": "Running",
    "network_Interface": "Wi-Fi"
}


### POST Request to Insert wrong Timeseries Data###
POST http://localhost:8000/data/
Content-Type: application/json

{
    "session_id": 1,
    "pc_recources": "High",
    "connection_data": "1",
    "application_data": "Running",
    "network_Interface": "Wi-Fi"
}

### Upload multiple files ###
POST http://localhost:8000/data/
Content-Type: multipart/form-data; boundary=--boundary

--boundary
Content-Disposition: form-data; name="files[]"; filename="file1.txt"

timestamp|displayName
1690273532611|Bluetooth Device

--boundary
Content-Disposition: form-data; name="files[]"; filename="file2.txt"

### get pc data ###
GET http://localhost:8000/pc/1/data?start=2023-07-25 10:20:16&end=2023-07-25 12:33:01

### get pc invalid data ###
GET http://localhost:8000/pc/1/data/GPU?start=2023-07-25 10:20:16&end=2023-12-25 10:33:01

### get pc time metrics
GET http://localhost:8000/pc/1/time-metrics/?start=2023-08-25 10:20:16&end=2023-12-25 10:33:01

### get application time metrics
GET http://localhost:8000/pc/1/application/jetbrains-toolbox/time-metrics/?start=2023-07-25 10:20:16&end=2023-12-25 10:33:01

### get application data
GET http://localhost:8000/pc/1/application/jetbrains-toolbox?start=2023-07-25 10:20:16&end=2023-09-25 10:33:01

### get list of applications
GET http://localhost:8000/pc/1/application/?start=2022-07-25 10:20:16&end=2023-12-25 10:33:01

### get forecast of available disk space
GET http://localhost:8000/pc/1/data/forecast/30

### get alerts
GET http://localhost:8000/alerts/1?start=2023-07-25 10:20:16&end=2023-09-25 10:33:01

### get all possible alerts
GET http://localhost:8000/alerts/all/1

### get alert justificatons for pc
GET http://localhost:8000/alerts/justify/1
Content-Type: application/json

    [
      "2023-08-02T16:51:12.816000",
      "2023-08-02T16:52:55.264000",
      "2023-08-02T16:54:28.269000",
      "2023-08-02T16:56:02.418000",
      "2023-08-02T16:57:33.203000",
      "2023-08-02T16:59:05.950000",
      "2023-08-02T17:00:45.167000",
      "2023-08-02T17:02:12.057000",
      "2023-08-02T17:03:34.686000",
      "2023-08-02T17:04:59.088000",
      "2023-08-02T17:06:18.701000",
      "2023-08-02T17:25:59.911000",
      "2023-08-02T17:27:42.133000",
      "2023-08-02T17:29:20.280000"
    ]


### get alert justificatons for an application
GET http://localhost:8000/alerts/justify/1?application=chrome
Content-Type: application/json

    [
      "2023-08-02T16:51:12.816000",
      "2023-08-02T16:52:55.264000",
      "2023-08-02T16:54:28.269000",
      "2023-08-02T16:56:02.418000",
      "2023-08-02T16:57:33.203000",
      "2023-08-02T16:59:05.950000",
      "2023-08-02T17:00:45.167000",
      "2023-08-02T17:02:12.057000",
      "2023-08-02T17:03:34.686000",
      "2023-08-02T17:04:59.088000",
      "2023-08-02T17:06:18.701000",
      "2023-08-02T17:25:59.911000",
      "2023-08-02T17:27:42.133000",
      "2023-08-02T17:29:20.280000"
    ]



### get application data bucketed ###
GET http://localhost:8000/pc/1/application/Adobe Desktop Service/bucket/?start=2023-07-25 10:20:16&end=2023-07-25 10:33:01&bucket_value=5 minutes

### get disks
GET http://localhost:8000/pc/1/disk

### get network interfaces and connections
GET http://localhost:8000/pc/1/network
###
GET http://localhost:8000/alerts?user_id=1
###
POST http://localhost:8000/alerts
Content-Type: application/json

{
  "custom_alert_list": [
    {
      "user_id": 1,
      "type": "Breaking threshold alert for PC RAM",
      "message": "Breaking threshold alert for PC RAM",
      "severity_level": 5,
      "conditions": [
        {
          "percentage_trigger_value": 0.05,
          "absolute_trigger_value": 0.05,
          "operator": ">",
          "column": "cpu",
          "application": "chrome",
          "detect_via_moving_averages": true
        }
      ]
    }
  ]
}

###
GET http://127.0.0.1:8000/pc/general_specs/1
###
GET http://127.0.0.1:8000/pc/resource_metrics/1
